name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Publish app
      run: dotnet publish -c Release

    - name: Archive published files
      run: |
        cd publish
        zip -r ../HeartMaker.zip .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: app
          path: HeartMaker.zip

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: HeartMaker.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
